# Generated by Django 2.2.4 on 2019-08-28 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190827_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_photo',
            new_name='photo',
        ),
    ]
