# Generated by Django 2.2.4 on 2019-08-26 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(default='', max_length=10),
        ),
    ]
