# Generated by Django 2.2.4 on 2019-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20190826_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default='Sam', max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='Malone', max_length=25),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='title',
            field=models.CharField(default='Mr.', max_length=10),
        ),
    ]
